routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function(){
	Auth::routes();
});

Route::middleware(['auth'])->group(function () {
	Route::group(
	[
		'prefix' => LaravelLocalization::setLocale(),
	    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
	],
	function(){
		Route::get('/', 'HomeController@index')->name('home');

		// Advertisements
		Route::get('/advertisements/list', 'AdvertisementController@list')->name('advertisements.list');
		Route::get('/advertisements/list/get', 'AdvertisementController@getList')->name('advertisements.getList');
		Route::resource('advertisements', 'AdvertisementController');
		Route::post('/advertisements/status/update', 'AdvertisementController@statusUpdate')->name('advertisements.statusUpdate');

		// Merchants
		Route::get('/merchants/list', 'MerchantController@list')->name('merchants.list');
		Route::get('/merchants/list/get', 'MerchantController@getList')->name('merchants.getList');
		Route::resource('merchants', 'MerchantController');
		Route::post('/merchants/status/update', 'MerchantController@statusUpdate')->name('merchants.statusUpdate');

		// Articles
		Route::get('/articles/list', 'ArticleController@list')->name('articles.list');
		Route::get('/articles/list/get', 'ArticleController@getList')->name('articles.getList');
		Route::resource('articles', 'ArticleController');
		Route::post('/articles/status/update', 'ArticleController@statusUpdate')->name('articles.statusUpdate');

		// Users
		Route::get('/users/list/{role?}', 'UserController@list')->name('users.list');
		Route::get('/users/list/get/{role?}', 'UserController@getList')->name('users.getList');
		Route::resource('users', 'UserController');
		Route::post('/users/status/update', 'UserController@statusUpdate')->name('users.statusUpdate');
		Route::post('/users/{user}/change-password', 'UserController@changePassword')->name('users.changepassword');
		Route::post('/users/{user}/modules', 'UserController@assignModules')->name('users.modules');

		// Account settings
		Route::get('/account/settings', 'AccountController@settings')->name('account.settings');
		Route::patch('/account/settings', 'AccountController@update')->name('account.update');
		Route::post('/account/change-password', 'AccountController@changePassword')->name('account.changepassword');

		// Comments
		Route::resource('comments', 'CommentController');

		// Images
		Route::post('/images/upload', 'ImageController@upload')->name('images.upload');

		// Tags
		Route::get('/tags/search', 'TagController@search')->name('tags.search');
	});
});

Route::get('/articlew/{article}', 'ArticleController@webView');

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;

use App\Module;
use App\Article;
use App\Report;
use App\Bookmark;
use App\UserMeta;
use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;


    public function findForPassport($username) {
        return $this->orWhere('email', $username)->orWhere('phone', $username)->first();
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
         'email', 'phone', 'password', 'role', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    
    /**
     * The attributes that are coming from meta table
     *
     * @var array
     */
    protected $appends  = [
         'firstname', 'lastname', 'avatar'
    ];

    /**
     * List of status
     */
    const STATUS_ACTIVE = 'active';
    const STATUS_INACTIVE = 'inactive';

    public static $statuses = [
        self::STATUS_ACTIVE,
        self::STATUS_INACTIVE
    ];

    /**
     * List of roles
     */
    const ROLE_SUPER_ADMIN = 'super admin';
    const ROLE_ADMIN = 'admin';
    const ROLE_USER = 'user';

    public static $roles = [
        self::ROLE_SUPER_ADMIN,
        self::ROLE_ADMIN,
        self::ROLE_USER
    ];

    /**
     * Get modules
     */
    public function modules()
    {
        return $this->belongsToMany(Module::class)
                    ->withPivot('action')
                    ->withTimestamps();
    }

    /**
     * Get access per module
     *
     * @param App\Module
     */
    public function access(Module $module)
    {
        return $this->modules->where('id', $module->id)
                             ->pluck('pivot.action')
                             ->toArray();
    }

    /**
     * Check role
     *
     * @return boolean 
     */
    public function hasRole($role)
    {
        return $this->role == $role;
    }

    /**
     * Get all created article
     */
    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    /**
     * Get meta
     */
    public function meta()
    {
        return $this->hasMany(UserMeta::class);
    }

    /**
     * Get specific meta data value
     */
    public function getMetaByKey($key)
    {
        return $this->meta->where('key', $key)->pluck('value')->first();
    }

    /**
     * Get photos
     */
    public function photos($limit = 0)
    {
        if (1 == $limit) {
            return $this->meta()->where('key', 'photo')->first();
        } elseif ($limit > 1) {
            return $this->meta()->where('key', 'photo')->get()->take($limit);
        } else {
            return $this->meta()->where('key', 'photo')->get();
        }
    }

     /**
     * Get all bookmarks
     */
    public function bookmarks()
    {
        return $this->hasMany(Bookmark::class);
    }

     /**
     * Get all reports
     */
    public function reports()
    {
        return $this->hasMany(Report::class);
    }

    /**
     * Get firstname
     *
     */
    public function getFirstnameAttribute()
    {
        return $this->getMetaByKey('firstname');
    }

    /**
     * Get firstname
     *
     */
    public function getLastnameAttribute()
    {
        return $this->getMetaByKey('lastname');
    }

    /**
     * Get firstname
     *
     */
    public function getAvatarAttribute()
    {
        return $this->getMetaByKey('avatar');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Module;
use DataTables;
use App\UserMeta;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Pagination max no. of items per page
     */
    public $itemsPerPage = 20;

    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('hasAccess', [User::class, 'view']);

        $users = User::orderBy('id', 'desc')
                             ->where(function ($query) use ($request) {
                                $query->where('role', '<>', User::ROLE_SUPER_ADMIN);

                                // Search by firstname or lastname
                                if (!empty($request->name)) {
                                    $query->whereHas('meta', function($query) use ($request) {
                                        $query->whereIn('key', ['firstname', 'lastname']);
                                        $query->where('value', 'LIKE','%'. $request->name .'%');
                                    }); 
                                }
                             })->paginate($this->itemsPerPage);

        // To add search on pagination
        $users->appends($request->all());

        // To repopulate search input
        $request->flash();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('hasAccess', [User::class, 'add']);
        $statuses = User::$statuses;

        return view('users.create', compact('modules', 'statuses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'firstname' => 'required|string|max:255',
            'lastname' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|unique:users',
            'status' => ['required', Rule::in(User::$statuses)],
            'password' => 'required|string|min:6|confirmed'
        ])->validate();

        $user = User::create([
            'email' => $request->email,
            'phone' => $request->phone,
            'role' => User::ROLE_ADMIN,
            'status' => $request->status,
            'password' => Hash::make($request->password)
        ]);

        $user->meta()->createMany([
            ['name' => 'FirstName', 'key' => 'firstname', 'value' =>  $request->firstname],
            ['name' => 'LastName', 'key' => 'lastname', 'value' =>  $request->lastname]
        ]);

        if (!Auth::user()->can('hasAccess', [User::class, 'edit'])) {
            return back()->with('status', 'success')
                         ->with('message', '<i class="fa fa-check-circle"></i> ' . __('User has been saved.'));
        }

        return redirect()->route('users.edit', ['user' => $user->id])
                         ->with('status_for', 'user_info')
                         ->with('status', 'success')
                         ->with('message', '<i class="fa fa-check-circle"></i> ' . __('User has been saved.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('hasAccess', [User::class, 'edit']);

        $statuses = User::$statuses;
        $modules = Module::all();
        $actions = Module::$actions;

        return view('users.edit', compact('user', 'statuses', 'modules', 'actions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        Validator::make($request->all(), [
            'firstname' => 'required|string|max:255',
            'lastname' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,' . $user->id,
            'phone' => 'required|string|unique:users,phone,' . $user->id,
            'status' => ['required', Rule::in(User::$statuses)],
        ])->validate();

        $user->fill($request->only(['email', 'phone', 'status']))->save();

        UserMeta::whereIn('key', ['firstname', 'lastname'])->where('user_id', $user->id)->delete();
        $user->meta()->createMany([
            ['name' => 'FirstName', 'key' => 'firstname', 'value' =>  $request->firstname],
            ['name' => 'LastName', 'key' => 'lastname', 'value' =>  $request->lastname]
        ]);

        return back()->with('status_for', 'user_info')
                     ->with('status', 'success')
                     ->with('message', '<i class="fa fa-check-circle"></i> ' . __('User has been updated.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('hasAccess', [User::class, 'delete']);
        $user->delete();
        return back()->with('status', 'success')
                     ->with('message', '<i class="fa fa-check-circle"></i> ' . __('User has been deleted.'));
    }

    /**
     * Change Password
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function changePassword(Request $request, User $user)
    {
        Validator::make($request->all(), [
            'password' => 'required|string|min:6|confirmed'
        ], [
            'password.required' => 'Password is required.'
        ])->validate();

        $user->password = Hash::make($request->password);
        $user->save();

        return back()->with('status_for', 'change_password')
                     ->with('status', 'success')
                     ->with('message', '<i class="fa fa-check-circle"></i> '. __('Password has been changed.'));
    }

    /**
     * Assign modules access.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function assignModules(Request $request, User $user)
    {
        if (!$request->has('modules_access')) {
            return back()->with('status_for', 'modules_access')
                         ->with('status', 'danger')
                         ->with('message', '<i class="fa fa-times-circle"></i> ' . __('Please select modules access.'));
        }

        $user->modules()->detach();

        foreach($request->modules_access as $module => $access) {
            foreach($access as $action) {
                $user->modules()->attach($module, ['action' => $action]);
            }
        }

        return back()->with('status_for', 'modules_access')
                         ->with('status', 'success')
                         ->with('message', '<i class="fa fa-check-circle"></i> ' . __('Modules access has been saved.'));
    }

    /**
     * Update status
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function statusUpdate(Request $request)
    {
        $users = User::whereIn('id', $request->input('users', []))->get();
        $checked = $request->has('checked') ? $request->checked : [];

        if ($users->isEmpty()) {
            return response()->json(['status' => 'danger', 'message' => __('Nothing has been updated!')]);
        }

        foreach($users as $user) {
            $user->status = in_array($user->id, $checked) ? User::STATUS_ACTIVE : User::STATUS_INACTIVE;
            $user->save();          
        }
           
        return response()->json(['status' => 'success', 'message' => __('Users has been updated')]);
    }

    /**
     * Displays datatables front end view
     *
     * @return \Illuminate\View\View
     */
    public function list($role = 'user')
    {
        $this->authorize('hasAccess', [User::class, 'view']);

        return view('users.datatables.index', compact('role'));
    }


    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getList($role = 'user')
    {
        $users = User::where('role', '=', $role)->get();

        return Datatables::of($users)
         ->addColumn('fullname', function(User $user){
            return $user->firstname . ' ' . $user->lastname;
         })
         ->editColumn('role', function(User $user){
            return ucfirst($user->role);
         })
         ->editColumn('status', function(User $user){
            $status = '<input type="checkbox" name="status[]" value="' . $user->id . '"';

            if (User::STATUS_ACTIVE == $user->status) {
                $status .= ' checked ';
            }

            $status .= '/>';

            return $status;
         })
         ->addColumn('action', function(User $user){
            $action = '';

            if(Auth::user()->can('hasAccess', [User::class, 'edit'])){
                $action .= '<a href="' . route('users.edit', ['user' => $user->id]) . '"><i class="fa fa-pencil"></i></a> ';

resources/views/users/forms/change_password.blade.php
<form method="POST" action="{{ route('users.changepassword', ['user' => $user->id]) }}">
    @csrf

    <div class="form-group  {{ $errors->has('password') ? 'has-error has-feedback' : '' }}">
        <label for="password" class="control-label">{{ __('New Password') }}</label>
        <input type="password" name="password" id="password" class="form-control" required>
        <p class="help-block">{{ __('Must be at least 6 characters.') }}</p>

        @if ($errors->has('password'))
            <span class="help-block text-left">{{ $errors->first('password') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('password_confirmation') ? 'has-error has-feedback' : '' }}">
        <label for="password_confirmation" class="control-label">{{ __('Confirm New Password') }}</label>
        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" required>

        @if ($errors->has('password_confirmation'))
            <span class="help-block text-left">{{ $errors->first('password_confirmation') }}</span>
        @endif
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success">{{ __('Change') }}</button>
    </div>
</form>

resources/views/users/forms/create.blade.php
<form method="POST" action="{{ route('users.store') }}">
    @csrf

    <div class="form-group  {{ $errors->has('firstname') ? 'has-error has-feedback' : '' }}">
        <label for="name" class="control-label">{{ __('First Name') }}</label>
        <input type="text" name="firstname" id="firstname" class="form-control" value="{{ old('firstname') }}" required>

        @if ($errors->has('firstname'))
            <span class="help-block text-left">{{ $errors->first('firstname') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('lastname') ? 'has-error has-feedback' : '' }}">
        <label for="name" class="control-label">{{ __('Last Name') }}</label>
        <input type="text" name="lastname" id="lastname" class="form-control" value="{{ old('lastname') }}" required>

        @if ($errors->has('lastname'))
            <span class="help-block text-left">{{ $errors->first('lastname') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('email') ? 'has-error has-feedback' : '' }}">
        <label for="email" class="control-label">{{ __('Email Address') }}</label>
        <input type="email" name="email" id="email" class="form-control" value="{{ old('email') }}" required>

        @if ($errors->has('email'))
            <span class="help-block text-left">{{ $errors->first('email') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('phone') ? 'has-error has-feedback' : '' }}">
        <label for="phone" class="control-label">{{ __('Phone') }}</label>
        <input type="phone" name="phone" id="phone" class="form-control" value="{{ old('phone') }}" required>

        @if ($errors->has('phone'))
            <span class="help-block text-left">{{ $errors->first('phone') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('status') ? 'has-error has-feedback' : '' }}">
        <label for="status" class="control-label">{{ __('Status') }}</label>
        <select name="status" id="status" class="form-control" required>
            <option value="">{{ __('Select') }}</option>
            @if(!empty($statuses))
                @foreach($statuses as $status)
                    <option value="{{ $status }}">
                        {{ ucfirst($status) }}
                    </option>
                @endforeach
            @endif
        </select>

        @if ($errors->has('status'))
            <span class="help-block text-left">{{ $errors->first('status') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('password') ? 'has-error has-feedback' : '' }}">
        <label for="password" class="control-label">{{ __('Password') }}</label>
        <input type="password" name="password" id="password" class="form-control" required>
        <p class="help-block">{{ __('Must be at least 6 characters.') }}</p>

        @if ($errors->has('password'))
            <span class="help-block text-left">{{ $errors->first('password') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('password_confirmation') ? 'has-error has-feedback' : '' }}">
        <label for="password_confirmation" class="control-label">{{ __('Confirm Password') }}</label>
        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" required>

        @if ($errors->has('password_confirmation'))
            <span class="help-block text-left">{{ $errors->first('password_confirmation') }}</span>
        @endif
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success">{{ __('Create') }}</button>
        @can('hasAccess', [App\User::class, 'view'])
            <a href="{{ route('users.index') }}" class="btn btn-default">{{ __('Cancel') }}</a>
        @endcan
    </div>
</form>

resources/views/users/forms/edit.blade.php
<form method="POST" action="{{ route('users.update', ['user' => $user->id]) }}">
    @csrf
    @method('PATCH')

    <div class="form-group  {{ $errors->has('firstname') ? 'has-error has-feedback' : '' }}">
        <label for="name" class="control-label">{{ __('First Name') }}</label>
        <input type="text" name="firstname" id="firstname" class="form-control" value="{{ old('firstname', $user->firstname) }}" required>

        @if ($errors->has('firstname'))
            <span class="help-block text-left">{{ $errors->first('firstname') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('lastname') ? 'has-error has-feedback' : '' }}">
        <label for="name" class="control-label">{{ __('Last Name') }}</label>
        <input type="text" name="lastname" id="lastname" class="form-control" value="{{ old('lastname', $user->lastname) }}" required>

        @if ($errors->has('lastname'))
            <span class="help-block text-left">{{ $errors->first('lastname') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('email') ? 'has-error has-feedback' : '' }}">
        <label for="email" class="control-label">{{ __('Email Address') }}</label>
        <input type="email" name="email" id="email" class="form-control" value="{{ old('email', $user->email) }}" required>

        @if ($errors->has('email'))
            <span class="help-block text-left">{{ $errors->first('email') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('phone') ? 'has-error has-feedback' : '' }}">
        <label for="phone" class="control-label">{{ __('Phone') }}</label>
        <input type="phone" name="phone" id="phone" class="form-control" value="{{ old('phone', $user->phone) }}" required>

        @if ($errors->has('phone'))
            <span class="help-block text-left">{{ $errors->first('phone') }}</span>
        @endif
    </div>

    <div class="form-group  {{ $errors->has('status') ? 'has-error has-feedback' : '' }}">
        <label for="status" class="control-label">{{ __('Status') }}</label>
        <select name="status" id="status" class="form-control" required>
            <option value="">Select</option>
            @if(!empty($statuses))
                @foreach($statuses as $status)
                    <option value="{{ $status }}"  
                    @if ($status == $user->status) {{ 'selected' }} @endif>
                        {{ ucfirst($status) }}
                    </option>
                @endforeach
            @endif
        </select>

        @if ($errors->has('status'))
            <span class="help-block text-left">{{ $errors->first('status') }}</span>
        @endif
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success">{{ __('Update') }}</button>
        @can('hasAccess', [App\User::class, 'view'])
            <a href="{{ route('users.index') }}" class="btn btn-default">{{ __('Cancel') }}</a>
        @endcan
    </div>
</form>